id: PD917DD6A
initial_creation_type: input
source_metadata:
  title: Yeshe Dorje
  language: en
  description: 'Texts by and about Yeshe Dorje (ye shes rdo rje), a prominent disciple
    of Nyala Pema Düdul who stayed at Lumorab monastery for many years along with
    Tertön Rangrik Dorje:'
  volume:
    bcaf50464e2d4c5a9891a70fcc6fa998:
      title: Prayer to the Lineage of Lumorab
      parent: Lineage Prayers
created_at: '2022-03-01T02:02:12.021227'
last_modified_at: '2022-03-01T02:02:12.021233'
